# Generated by Django 4.0 on 2022-08-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='visitors',
            field=models.IntegerField(default=0),
        ),
    ]
